.github/workflows/update-toolhive-reference.yml
scripts/update-toolhive-reference.sh

This adds a workflow to pull the CLI and API reference docs from the latest ToolHive release, and opens a PR if anything has changed.
Halfway to closing #1, next step is to get the toolhive repo to call it as part of the release workflow.

Add release update workflow

---

.github/workflows/update-toolhive-reference.yml

The create-pull-request action expects to be on the base branch

Fix reference update workflow

---

docs/toolhive/guides-cli/install.mdx
docs/toolhive/index.mdx
docs/toolhive/tutorials/quickstart.mdx

- Add WInGet method to the quickstart tutorial
- Note the need to start a new terminal in Windows
- Note that Homebrew works on Linux too
- Simplify *nix binary install commands

Minor updates to install instructions

---

package-lock.json
package.json

Resolves the CVEs in `webpack-dev-server < 5.2.1`
It's a transitive dependency of `@docusaurus/core`, and they don't plan to bump it until v4 (see facebook/docusaurus#11252).
It's only used for the local preview server, so risk of overriding is low, and I've tested without issues.

Override webpack-dev-server version

---

docs/toolhive/guides-cli/install.mdx

Windows locks the exe file while it's running, so WinGet can't replace it if any servers are running.

Add note about stopping before upgrade on Windows

---

docs/toolhive/guides-cli/manage-mcp-servers.md

Fix the `rm` command example

---

.github/instructions/writing-style.instructions.md

Introduces a custom instructions file for Copilot to use with md/mdx files.
This should make writing and reviewing docs easier for contributors.

Add Copilot custom instructions

---

docs/toolhive/guides-cli/client-configuration.md
docs/toolhive/reference/client-compatibility.mdx
docs/toolhive/tutorials/quickstart.mdx

Updates to reflect the removal of auto-discovery in stacklok/toolhive#811 and the new setup/status commands in stacklok/toolhive#821
Merge after v0.1.0 is released.

Update client configuration docs

---

.github/workflows/update-toolhive-reference.yml
.markdownlint-cli2.jsonc
.vscode/settings.json
docs/toolhive/guides-k8s/run-mcp-k8s.md
docs/toolhive/reference/crd-spec.mdx
scripts/update-toolhive-reference.sh
static/api-specs/crd-api.md

Adds the CRD reference into the reference section, sourcing the spec being generated in the main toolhive repo.
Updated update-toolhive-reference.sh script to take the release tag as a parameter and get the spec file from toolhive-operator-crds releases.
Once merged, will update the workflow on the toolhive repo to remove the condition on the release tag.

Add the CRD reference and automation

---

.markdownlint.json
README.md
docs/toolhive/guides-cli/client-configuration.md
docs/toolhive/guides-cli/custom-permissions.mdx
docs/toolhive/guides-cli/install.mdx
docs/toolhive/guides-cli/run-mcp-servers.mdx
docs/toolhive/guides-cli/secrets-management.mdx
docs/toolhive/guides-k8s/deploy-operator-helm.md
docs/toolhive/guides-k8s/run-mcp-k8s.md
docs/toolhive/tutorials/quickstart.mdx
docs/toolhive/tutorials/toolhive-operator.mdx

This eliminates clutter in the in-page table of contents, and reduces overall page lengths.
Before:
After:

Use collapsible blocks for troubleshooting notes

---

src/pages/index.tsx

Adds our new SQLite MCP server to the landing page.

Add SQLite MCP to landing page

---

docs/toolhive/guides-cli/run-mcp-servers.mdx

New in v0.1.3, can optionally use streamable-http for stdio servers.

Add note about proxy mode for stdio

---

docs/toolhive/guides-cli/run-mcp-servers.mdx
docs/toolhive/tutorials/quickstart.mdx

AFAIK we have 2 ports: the proxy port in which ToolHive runs and a hardcoded port that may be used by an MCP server. For the second one, the current flag should be `--target-port` instead of `--port`. Changed the only reference I could find in docs.
Also, there was a small typo in the quickstart guide in the ports. The text was talking about port `49226` but the port shown in the example was port `15266`.

Specify --target-port on docs and match port on quickstart guide

---

docs/toolhive/guides-cli/custom-permissions.mdx

Remove allow_transport from network permissions

---

docs/toolhive/concepts/registry-criteria.md
docs/toolhive/guides-cli/registry.md

Moves the "Contribute to the registry" section from the CLI section out to the Concepts page.
N/A
N/A

Move registry contribution to the concepts page

---

docs/toolhive/guides-ui/install.mdx

Add troubleshooting note for the Linux tray icon

---

docs/toolhive/_partials/_client-compat-table.md
docs/toolhive/reference/client-compatibility.mdx

Updated the client compatibility for VS Code noting ToolHive v0.2.0's support for Code v1.102+ and the new config file.
Related to stacklok/toolhive#1037 and stacklok/toolhive#1091
Updates the note originally added in #58
- Rationale: 404's are the enemy! You can test these in the Vercel preview build (push your branch or run `vercel`)

Update VS Code compatibility

---

docs/toolhive/guides-ui/install.mdx

Updates the UI install doc to reference the new dedicated settings screen.
Also fixed a bad link to the x64 DMG.
stacklok/toolhive-studio#622
- Rationale: 404's are the enemy! You can test these in the Vercel preview build (push your branch or run `vercel`)

Document new UI settings screen, other minor polish

---

docs/toolhive/guides-cli/run-mcp-servers.mdx

Remove --tools example showing comma-separated list because we don't support that with the current implementation.
https://github.com/stacklok/toolhive/issues/1239

Use the --tools flag multiple times

---

docs/toolhive/guides-k8s/intro.md
docs/toolhive/guides-k8s/run-mcp-k8s.md

- Amended some examples to use StreamableHTTP as SSE is deprecated
- Added a StreamableHTTP transport flow with the SSE section
- Removes `SSE` from the high-level diagram flow as `http` is enough and can cover Streamable HTTP too.

docs: adds streamablehttp docs for K8s

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
DCO.md
SECURITY.md

Adds OSS governance docs to the repo: contributing guide, CoC, and security policy.

Add governance docs

---

.github/copilot-instructions.md
.github/prompts/doc-review.prompt.md
.markdownlint-cli2.jsonc

Updates the Copilot instructions file with more details and moved it to the main `copilot-instructions.md` since it's the only file supported by Copilot code reviews.
Also added a custom `/doc-review` prompt.

Update Copilot instructions

---

docs/toolhive/_partials/_client-compat-table.md
docs/toolhive/reference/client-compatibility.mdx

Updates the minimum Cline version to 3.17.10. Streamable HTTP support was fixed as of this version.
stacklok/toolhive#1519

Update Cline version

---

.github/copilot-instructions.md
CLAUDE.md
docs/theme-preview.mdx
docs/toolhive/guides-cli/build-containers.mdx
docs/toolhive/guides-cli/custom-permissions.mdx
docs/toolhive/guides-cli/group-management.md
docs/toolhive/guides-cli/index.mdx
docs/toolhive/guides-cli/network-isolation.mdx
docs/toolhive/guides-cli/run-mcp-servers.mdx
docs/toolhive/guides-cli/secrets-management.mdx
docs/toolhive/guides-cli/telemetry-and-metrics.md
docs/toolhive/guides-k8s/intro.md
docs/toolhive/guides-k8s/run-mcp-k8s.md
docs/toolhive/guides-ui/index.mdx
docs/toolhive/guides-ui/install.mdx
docs/toolhive/guides-ui/network-isolation.mdx
docs/toolhive/guides-ui/secrets-management.md
docs/toolhive/tutorials/quickstart-cli.mdx
docs/toolhive/tutorials/quickstart-k8s.mdx
docs/toolhive/tutorials/quickstart-ui.mdx
docusaurus.config.ts

Disables the MDX v1 compatibility options for comments and admonitions.
This requires the updated admonition title syntax using square brackets.
See https://docusaurus.io/docs/migration/v3#turn-off-mdx-v1-compat

Update admonition title syntax

---

docs/toolhive/guides-cli/install.mdx
docs/toolhive/guides-cli/run-mcp-servers.mdx
docs/toolhive/guides-ui/install.mdx
docs/toolhive/reference/cli/thv.md
docs/toolhive/tutorials/quickstart-cli.mdx
docs/toolhive/tutorials/quickstart-ui.mdx

DO NOT MERGE until next release
Document Colima support.
https://github.com/stacklok/toolhive/pull/1492

Add Colima

---

docs/toolhive/guides-k8s/run-mcp-k8s.md

Fixes some K8s manifest examples, seems `targetPort` is now required for `streamable-http` transport in the latest Operator.

Add required `targetPort` attribute

---

docs/toolhive/guides-cli/manage-mcp-servers.md
docs/toolhive/guides-cli/run-mcp-servers.mdx

Added the support docs for remote mcp servers in run-mcp-servers.md and manage-mcp-servers.md

CLI: Add remote server docs

---

scripts/install-thv.sh

Temporarily hardcoding the Vercel install script to work aorund the new v0.3.0+ behavior of exiting early if a container runtime isn't found.

Temporary fix for new early exit behavior in thv

---

docs/toolhive/_partials/_remote-mcp-auth-examples.md
docs/toolhive/guides-cli/manage-mcp-servers.md
docs/toolhive/guides-ui/network-isolation.mdx
docs/toolhive/guides-ui/run-mcp-servers.mdx

Some minor polish:
- Removed duplicate heading from `guides-ui/run-mcp-servers` page
- Fixed order of operations to match the UI order
- Moved the remote server auth examples to a partial so it could be included in both sections (anchor link wasn't working across tabs)
- Corrected an old note about network isolation only being supported for registry servers

Minor improvements and fixes for UI docs

---

docs/toolhive/guides-cli/custom-permissions.mdx
docs/toolhive/guides-cli/network-isolation.mdx

DO NOT MERGE until next release
Updated the network isolation guides to include the new inbound configuration option.
https://github.com/stacklok/toolhive/pull/2030

Add docs for inbound network isolation
